### ISSUE TITLE
TypeError: 'newline' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by djiesamsoe** [GiiVeloper24/WebScrapeLzd#3]
I run as instructed, but I found a problem when the 'scrape' button click.
error looks like this:

```
File "/Users/Documents/WebScrapeLzd-master/webscrape/webscrape.py", line 95, in run_lazada_scrape
    self.myfile = open(str(uuid.uuid4()) + ".csv", 'w', newline='')
TypeError: 'newline' is an invalid keyword argument for this function
```
Thanks

**Comment by MrBars24** [comment]
I've tried what you said and it works fine for me. But still I do some changes removing newline='' and added lineterminator='\n' . hoping it will work fine for you.

**Comment by djiesamsoe** [comment]
Thanks for your reply and update.
I tried with the latest file, but still the same error occurs.
> Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "home.py", line 167, in <lambda>
    command=lambda:self.scrape_web(categ,self.vars))
  File "home.py", line 373, in scrape_web
    self.wscrape.run_lazada_scrape(categ,prod_dictionary)
  File "/Users/Documents/WebScrapeLzd-master/webscrape/webscrape.py", line 95, in run_lazada_scrape
    self.myfile = open(str(uuid.uuid4()) + ".csv", 'w', newline='')
TypeError: 'lineterminator' is an invalid keyword argument for this function

**Comment by MrBars24** [comment]
Hmm.. maybe it's because of the version of your python because I am using python 3.4

**Comment by qzj1103** [comment]
hi i try you project in my computer,  as i press `scrape ` and i get 
WebScrape Imported
Cannot Retrieve Max Page

Scraping at electronics - computer accessories
Scraping 1 out of 1
Done Scraping 

this in my console. i open the csv file , and the file is empty.  could you tell me how to do. what that means 'Cannot Retrieve Max Page' ?
